time_grid:
    time_min: 0
    time_max: 3
    time_bins: 50
    time_inj : 2

gamma_grid:
    log_gamma_min: 2
    log_gamma_max: 6
    gamma_bins: 50

emission_region:
    log_R: 15.5
    R_unit: 'cm'
    delta: 20
    log_B: -1
    B_unit: 'G'
    t_esc: 1.5
    z: 0.4

injected_spectrum:
    type: 'ExponentialCutoffPowerLaw'
    log_Norm: 4
    Norm_unit: 'cm-3'
    index: 2.2
    log_gamma_c: 4.5
